<h1>Johns Hopkins University</h1>

<img src="<?php require_once('etc/functions.php'); echo get_logo('JHU'); ?>" alt="Johns Hopkins University Logo" class='instlogo'/>

<p>Website: <a href="http://www.jhu.edu">http://www.jhu.edu</a>.</p>

<p>From <a href="https://en.wikipedia.org/wiki/Johns_Hopkins_University">Wikipedia</a>:</p>

<p>The Johns Hopkins University (commonly referred to as Johns Hopkins, JHU, or simply Hopkins) is a private research university in Baltimore, Maryland. Founded in 1876, the university was named after its first benefactor, the American entrepreneur, abolitionist, and philanthropist Johns Hopkins. His $7 million bequest—of which half financed the establishment of The Johns Hopkins Hospital—was the largest philanthropic gift in the history of the United States at the time. Daniel Coit Gilman, who was inaugurated as the institution's first president on February 22, 1876, led the university to revolutionize higher education in the U.S. by integrating teaching and research.</p>

<p>Johns Hopkins is organized into ten divisions on campuses in Maryland and Washington, D.C. with international centers in Italy, China, and Singapore. The two undergraduate divisions, the Krieger School of Arts and Sciences and the Whiting School of Engineering, are located on the Homewood campus in Baltimore's Charles Village neighborhood.The medical school, the nursing school, and the Bloomberg School of Public Health are located on the Medical Institutions campus in East Baltimore. The university also consists of the Peabody Institute, the Applied Physics Laboratory, the Paul H. Nitze School of Advanced International Studies, the education school, the Carey Business School, and various other facilities.</p>

<p>The first research university in the United States and one of the founding members of the American Association of Universities, Johns Hopkins has been ranked among the world’s top universities throughout its history. For 35 consecutive years, it has been ranked #1 among U.S. academic institutions by the National Science Foundation in terms of total scientific, medical, and engineering research and development spending. Johns Hopkins is also among the top 20 in the tables of ARWU, QS, THE and U.S. News (Global), and ranked 12th in the U.S. News' national ranking for 2014.Over the course of almost 140 years, 36 Nobel Prize winners have been affiliated with Johns Hopkins (the first was U.S. President Woodrow Wilson, who received his Ph.D. in history and political science from the university). Founded in 1883, the Blue Jays men’s lacrosse team has captured 44 national titles and joined the Big Ten Conference as an affiliate member in 2014.</p>
