<h1>National Astronomical Observatories, Chinese Academy of Sciences</h1>

<img src="<?php require_once('etc/functions.php'); echo get_logo('NAOC'); ?>" alt="National Astronomical Observatories, Chinese Academy of Sciences Logo" class='instlogo'/>

<p>Website: <a href="http://english.nao.cas.cn/">http://english.nao.cas.cn</a>.</p>

<p>The National Astronomical Observatories of the Chinese Academy of Sciences (NAOC) was officially founded in April 2001 through the merger of four observatories, three observing stations and one research center, all under the Chinese Academy of Sciences (CAS). NAOC is headquartered in Beijing and has four subordinate units across the country: the Yunnan Observatories (YNAO), the Nanjing Institute of Astronomical Optics and Technology (NIAOT), the Xinjiang Astronomical Observatory (XAO) and the Changchun Observatory. The Purple Mountain Observatory (PMO) and the Shanghai Astronomical Observatory (SHAO) are separate CAS institutes, but are subject to NAOC’s academic strategies and research policies.</p>

<p>The headquarters of NAOC (hereafter, “NAOC”) is located in Beijing and was formerly called the Beijing Astronomical Observatory. It was established in 1958. Aiming at the forefront of astronomical science, NAOC conducts cutting-edge astronomical studies, operates major national facilities and develops state-of-the-art technological innovations. Applying astronomical methods and knowledge to fulfill national interests and needs is also an integral part of the mission of NAOC.   </p>

<p>NAOC’s main research involves cosmological large-scale structures, the formation and evolution of galaxies and stars, high-energy astrophysics, solar magnetism and activity, lunar and deep space exploration, and astronomical instrumentation. NAOC has seven major research departments in the areas of optical astronomy, radio astronomy, galaxies and cosmology, space science, solar physics, lunar and deep space exploration, and applications in astronomy. These departments encompass more than 50 research groups and house the CAS Key Laboratories of Optical Astronomy, Solar Activity, and Lunar and Deep-Space Exploration. NAOC also has three major observing stations: Xinglong, for optical and infrared astronomy; Huairou, for solar magnetics; and Miyun, for radio astronomy and satellite data downlinks. NAOC has been deeply involved in the China Lunar Exploration Program, from designing and managing lunar exploration satellite payload systems, to receiving, storing and analyzing the data transmitted by these satellites from space. NAOC also has a GPU super-cluster computing facility with 85 nodes at a peak computing speed of up to 280 teraflops. NAOC also publishes Research in Astronomy and Astrophysics (RAA), a journal catalogued by SCI.</p>

<p>As of 2013, the number of staff affiliated with NAOC was about 600. Among its staff are seven CAS members, 100 research professors and 160 associate research professors. NAOC currently has 40 postdoctoral research fellows, along with 137 doctoral students and 82 master’s students.</p>

<p>NAOC constructs and operates a wide variety of facilities at the national level. The Large Sky Area Multi-Object Fiber Spectroscopy Telescope (LAMOST), also known as the Guoshoujing Telescope, which is equipped with large FOV optics and up to 4,000 fibers on the focal plane, was put into scientific use in Sept. 2013. The world’s largest single-dish, Five-hundred-meter Aperture Spherical Telescope (FAST), is now under construction in Guizhou Province, in southwest China. Construction has already been completed on the 21-Centimeter Array (21CMA), which will be used to study the cosmic Epoch of Reionization, as well as on the Chinese Solar Radio Heliograph (CSRH). In the future, NAOC hopes to build remote and better sites in Yangbajing and Ali, Tibet for new optical-infrared and submillimeter facilities.</p>

<p>NAOC actively cooperates with scientists around the world. Together with its Chinese counterparts in other CAS institutes and Chinese universities, NAOC has vigorously participated in building the Thirty-meter-telescope (TMT) International Observatory. NAOC also initiated the Square Kilometre Array (SKA) international project with 10 other countries. The CAS South American Center for Astronomy, also known as the China-Chile Joint Research Center for Astronomy, was recently established in Santiago, Chile. NAOC has a South American station located in Argentina that runs its Satellite Laser Ranging (SLR) project. In addition, the China-Argentina 40m Radio Telescope is under construction. NAOC also engages in collaboration through the Chinese-French Origins International Associated Laboratory and the East Asian Core Observatories Association.</p>
